### ISSUE TITLE
Update example doc

### ISSUE THREAD

**Issue by ppbeautyacademy** [ShipEngine/shipengine-java#18]
I think there is a mistake in the example of the getRatesWithShipmentDetails function. It should be updated with the correct example. Currently, it's using createLabelFromShipmentDetails

**Comment by sushithegreat** [comment]
Fixed in [this commit](https://github.com/ShipEngine/shipengine-java/commit/f265b21fd7c0d6ef9a5b3f087b9e36d100618c61)
