### ISSUE TITLE
API call error throw ClassCastException (should be ShipengineException)

### ISSUE THREAD

**Issue by ducnh298** [ShipEngine/shipengine-java#19]
Your response return Map<String, String+ArrayList>:

![unknown](https://user-images.githubusercontent.com/108881014/194822419-bd735188-3128-4cff-bfe4-a487af2d97c4.png)

In src/main/java/com/shipengine/InternalClient.java
func checkResponseForErrors( ) 
you initiate a Map<String, ArrayList> to get that response:

![11unk11nown](https://user-images.githubusercontent.com/108881014/194824783-0ab4de1b-917d-4b17-8241-37141a548fb0.png)

then this ClassCastException's always thrown (should be ShipengineException)   

`class java.lang.String cannot be cast to class java.util.ArrayList (java.lang.String and java.util.ArrayList are in module java.base of loader 'bootstrap') `

Please help me solve this

**Comment by ducnh298** [comment]
Hello there!

Looks like my PR doesn't solve anything (of course, my bad in checking back
code)
Is there any way to fix this issue,
Or maybe the sandbox API key i'm using, its response is different from
production.

Looking forward to hearing from you soon!

Best,
Duc Nguyen Huu

**Comment by sushithegreat** [comment]
I believe you'll want to do this:
`List<Map<String, String>> result = shipengine.validateAddresses(unvalidatedAddress);`

I've updated the readme as well, let me know if that does not resolve your issue.

**Comment by ducnh298** [comment]
No, it isn't my issue.
You get it wrong.
Please take a look at my first comment. I have 2 pics to describe it.
I have issue in file "src/main/java/com/shipengine/InternalClient.java"
at function "checkResponseForErrors( )"


Vào Th 6, 14 thg 10, 2022 vào lúc 04:21 Susi Rathmann <
***@***.***> đã viết:

**Comment by sushithegreat** [comment]
You should not be calling any of the methods in the InternalClient directly, only using methods in ShipEngine. What does your actual code look like?

**Comment by ducnh298** [comment]
Yes I'm using methods in ShipEngine.

But I have to use debug mode, create a breakpoint in InternalClient to get
the correct response (such as incorrect address, carrier, service, etc...).
Otherwise, 100% times when Shipengine meet error, this exception is thrown:
"class java.lang.String cannot be cast to class java.util.ArrayList
(java.lang.String and java.util.ArrayList are in module java.base of loader
'bootstrap')"

Which prevents me from getting specific error messages, to know what is
wrong with my shipment details.

**Comment by sushithegreat** [comment]
I'm not able to reproduce this error. Can you post an example line of code?

**Comment by ducnh298** [comment]
I've explained and post 2 pics for this issue in my first comment. You can check that.

**Comment by ducnh298** [comment]
Hi!
Can you release new version maven's dependency (include this issue fixed) ?

**Comment by sushithegreat** [comment]
I'll publish a release ASAP, just waiting on some access control changes on our end

**Comment by ducnh298** [comment]
Great, thanks!

Vào 5:10, Th 7, 22 thg 10, 2022 Susi Rathmann ***@***.***> đã
viết:
